#!/bin/sh

filename=$1	## .hic file generated by juicer tools pre
outdir=$2	## Output directory
tag=$3		## Output file prefix
param1=$4	## observed/oe
param2=$5	## Normalization (NONE/VC/VC_SQRT/KR)	
param3=$6	## resolution

#### For distance decay plot, run script at 5000bp resolution


mkdir -p $outdir
for i in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16
do
 java -jar juicer_tools_1.19.02.jar dump $param1 $param2 $filename $i $i BP $param3 $outdir/chr$i\.txt 
 sort -k1n -k2n $outdir/chr$i\.txt | awk -v var=$i -F "\t" '{print var"\t"$0}' > $outdir/temp.txt
 mv $outdir/temp.txt $outdir/chr$i\.txt
 if [ $i = 1 ]; then
  mv $outdir/chr$i\.txt $outdir/$tag\_intrainteractions.txt
 else
  cat $outdir/chr$i\.txt >> $outdir/$tag\_intrainteractions.txt
  rm $outdir/chr$i\.txt 
 fi
done
