#!/bin/sh

filename=$1	## .hic file generated by juicer tools pre
outdir=$2	## Output directory
tag=$3		## Output file prefix
param1=$4	## observed/oe
param2=$5	## Normalization (NONE/VC/VC_SQRT/KR)	
param3=$6	## resolution
ct=1

mkdir -p $outdir
for i in {1..16}
do
for j in {1..16}
do
 if (( $i > $j ))
 then
  echo $i$j
 java -jar juicer_tools_1.19.02.jar dump $param1 $param2 $filename $i $j BP $param3 $outdir/chr$i$j\.txt 
 sort -k1n -k2n $outdir/chr$i$j\.txt | awk -v var=$i -v var2=$j -F "\t" '{print var2"\t"$1"\t"var"\t"$2"\t"$3}' > $outdir/temp.txt
 sort -k1n -k2n $outdir/chr$i$j\.txt | awk -v var=$i -v var2=$j -F "\t" '{print var"\t"$2"\t"var2"\t"$1"\t"$3}' > $outdir/temp2.txt
 cat $outdir/temp.txt $outdir/temp2.txt > $outdir/chr$i$j\.txt
 rm $outdir/temp.txt $outdir/temp2.txt
 if [ $ct -eq 1 ]; then
  mv $outdir/chr$i$j\.txt $outdir/$tag\_interinteractions.txt
  ct=$((ct+1))
 else
  cat $outdir/chr$i$j\.txt >> $outdir/$tag\_interinteractions.txt
  rm $outdir/chr$i$j\.txt 
 fi
fi
done
done
awk -v var=$param3 -F "\t" '{print "chr"$1"\t"$2"\t"$2+var"\t""chr"$3"\t"$4"\t"$4+var"\t"$5}' $outdir/$tag\_interinteractions.txt > $outdir/$tag\_interinteractions_interval.txt 


#### Telomere clustering - Inter interactions at 50kb resolution

bedtools intersect -F 1 -wo -a $outdir/$tag\_interinteractions_interval.txt -b telomere.bed | awk -F "\t" '{print $4"\t"$5"\t"$6"\t"$1"\t"$2"\t"$3"\t"$7"\t"$8"\t"$9"\t"$10"\t"$11}' > $outdir/$tag\_telomere_interaction_temp1.txt

bedtools intersect -F 1 -wo -a $outdir/$tag\_telomere_interaction_temp1.txt -b telomere.bed | awk -F "\t" '{print $1"\t"$2"\t"$3"\t"$15"\t"$4"\t"$5"\t"$6"\t"$11"\t"$7}' > $outdir/$tag\_telomere_interaction_50kb.txt



#### Telomere sub-clusters - Inter interactions at 10kb resolution

bedtools intersect -F 1 -wo -a $outdir/$tag\_interinteractions_interval.txt -b telomere.bed > $outdir/$tag\_inter_telomere.txt



#### Centromere interactions circos - Inter interactions at 5kb resolution

awk -F "\t" '{print $1"\t"$2"\t"$2+5000"\t"$5}' $outdir/$tag\_interinteractions.txt > $outdir/$tag\_leftinterinteractions.txt
bedtools intersect -wao -a $outdir/$tag\_leftinterinteractions.txt -b sc3_5kb_bins_with_cen.bed | cut -f1-4,8-9 > $outdir/$tag\_leftinterinteractions_id.txt

awk -F "\t" '{print $3"\t"$4"\t"$4+5000"\t"$5}' $outdir/$tag\_interinteractions.txt > $outdir/$tag\_ctrl_rightinterinteractions.txt
bedtools intersect -wao -a $outdir/$tag\_ctrl_rightinterinteractions.txt -b sc3_5kb_bins_with_cen.bed | cut -f1-4,8-9 > $outdir/$tag\_rightinterinteractions_id.txt

paste -d "\t" $outdir/$tag\_leftinterinteractions_id.txt $outdir/$tag\_rightinterinteractions_id.txt > $outdir/$tag\_interinteractions_withid.txt
